// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"bg-gray-50 shadow-md\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-between items-center h-16\"><!-- Logo --><div class=\"flex-shrink-0\"><img class=\"h-8 w-auto\" src=\"https://tailwindui.com/img/logos/mark.svg?color=violet&amp;shade=500\" alt=\"Your Company\"></div><!-- Navigation Items --><div class=\"flex justify-center flex-grow\"><div class=\"flex space-x-4\"><a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">These</a> <a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">Are</a> <a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">Example</a> <a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">Links</a></div></div><!-- Profile Image --><div class=\"flex-shrink-0\"><img class=\"h-8 w-8 rounded-full\" src=\"https://randomuser.me/api/portraits/men/1.jpg\" alt=\"Profile Image\"></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
