// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"bg-gray-50 shadow-md\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-between items-center h-16\"><!-- Logo --><div class=\"flex-shrink-0\"><img class=\"h-8 w-auto\" src=\"https://tailwindui.com/img/logos/mark.svg?color=violet&amp;shade=500\" alt=\"Your Company\"></div><!-- Navigation Items --><div class=\"flex justify-center flex-grow\"><div class=\"flex space-x-4\"><a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">These</a> <a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">Are</a> <a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">Example</a> <a href=\"#\" class=\"text-gray-900 hover:text-gray-700 px-3 py-2 text-sm font-medium\">Links</a></div></div><!-- Profile Image --><div class=\"flex-shrink-0\"><img class=\"h-8 w-8 rounded-full\" src=\"https://randomuser.me/api/portraits/men/1.jpg\" alt=\"Profile Image\"></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
