// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package inputs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"date-rate/app/components/svgs"
	"github.com/joho/godotenv"
	"log"
	"os"
)

func ButtonGoogleSignIn() templ.Component {
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	appUrl := os.Getenv("APP_URL")
	return buttonGoogleSignIn(appUrl)
}

func buttonGoogleSignIn(appUrl string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.JSONScript("appUrl", appUrl).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/dist/pocketbase/dist/pocketbase.umd.js\"></script><script type=\"text/javascript\">\n    const signInWithGoogle = async () => {\n        const appUrl = JSON.parse(document.getElementById('appUrl').textContent);\n        const pb = new PocketBase(appUrl);\n        const authData = await pb.collection('users').authWithOAuth2({provider: 'google'});\n        const response = await fetch(`${appUrl}/login/oauth2`, {\n            method: 'POST',\n            headers: {\n                'Content-Type': 'application/json',\n            },\n            body: JSON.stringify(authData),\n        })\n        location.reload();\n    }\n    </script><button type=\"button\" onclick=\"signInWithGoogle()\" class=\"border border-gray-400 rounded flex gap-2 py-1.5 px-2 items-center justify-center font-medium focus:outline-1 focus:outline-offset-2 focus:outline-blue-400 text-gray-700\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = svgs.GoogleLogoSvg("h-6 w-6").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span>Google</span></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
