// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package inputs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "date-rate/app/components/svgs"

func ButtonGoogleSignIn() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/dist/pocketbase/dist/pocketbase.umd.js\"></script><script type=\"text/javascript\">\n        const signInWithGoogle = async () => {\n            const pb = new PocketBase('http://127.0.0.1:8090');\n            const authData = await pb.collection('users').authWithOAuth2({provider: 'google'});\n            const response = await fetch('http://127.0.0.1:8090/login/oauth2', {\n                    method: 'POST',\n                    headers: {\n                            'Content-Type': 'application/json',\n                        },\n                    body: JSON.stringify(authData),\n                })\n            location.reload();\n        }\n    </script><button type=\"button\" onclick=\"signInWithGoogle()\" class=\"border border-gray-400 rounded flex gap-2 py-1.5 px-2 items-center justify-center font-medium focus:outline-1 focus:outline-offset-2 focus:outline-blue-400 text-gray-700\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = svgs.GoogleLogoSvg("24", "24").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span>Google</span></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
